class Zone:
    pass


class Keyboard(Zone):
    FunctionKeys = 'function-keys'
    MainKeyboard = 'main-keyboard'
    Keypad = 'keypad'
    NumberKeys = 'number-keys'
    MacroKeys = 'macro-keys'
    pass


class Mouse(Zone):
    Wheel = 'wheel'
    Logo = 'logo'
    Base = 'base'
    pass


class Headset(Zone):
    EarCups = 'earcups'
    pass


class Indicator(Zone):
    One = 'one'
    pass


class ZonedRGB(Zone):
    One = 'one'
    Two = 'two'
    Three = 'three'
    Four = 'four'
    Five = 'five'
    Six = 'six'
    Seven = 'seven'
    Eight = 'eight'
    Nine = 'nine'
    Ten = 'ten'
    Eleven = 'eleven'
    Twelve = 'twelve'
    Thirteen = 'thirteen'
    Fourteen = 'fourteen'
    Fifteen = 'fifteen'
    Sixteen = 'sixteen'
    Seventeen = 'seventeen'
    Eighteen = 'eighteen'
    Nineteen = 'nineteen'
    Twenty = 'twenty'
    TwentyOne = 'twenty-one'
    TwentyTwo = 'twenty-two'
    TwentyThree = 'twenty-three'
    TwentyFour = 'twenty-four'
    TwentyFive = 'twenty-five'
    TwentySix = 'twenty-six'
    TwentySeven = 'twenty-seven'
    TwentyEight = 'twenty-eight'
    TwentyNine = 'twenty-nine'
    Thirty = 'thirty'
    ThirtyOne = 'thirty-one'
    ThirtyTwo = 'thirty-two'
    ThirtyThree = 'thirty-three'
    ThirtyFour = 'thirty-four'
    ThirtyFive = 'thirty-five'
    ThirtySix = 'thirty-six'
    ThirtySeven = 'thirty-seven'
    ThirtyEight = 'thirty-eight'
    ThirtyNine = 'thirty-nine'
    Forty = 'forty'
    FortyOne = 'forty-one'
    FortyTwo = 'forty-two'
    FortyThree = 'forty-three'
    FortyFour = 'forty-four'
    FortyFive = 'forty-five'
    FortySix = 'forty-six'
    FortySeven = 'forty-seven'
    FortyEight = 'forty-eight'
    FortyNine = 'forty-nine'
    Fifty = 'fifty'
    FiftyOne = 'fifty-one'
    FiftyTwo = 'fifty-two'
    FiftyThree = 'fifty-three'
    FiftyFour = 'fifty-four'
    FiftyFive = 'fifty-five'
    FiftySix = 'fifty-six'
    FiftySeven = 'fifty-seven'
    FiftyEight = 'fifty-eight'
    FiftyNine = 'fifty-nine'
    Sixty = 'sixty'
    SixtyOne = 'sixty-one'
    SixtyTwo = 'sixty-two'
    SixtyThree = 'sixty-three'
    SixtyFour = 'sixty-four'
    SixtyFive = 'sixty-five'
    SixtySix = 'sixty-six'
    SixtySeven = 'sixty-seven'
    SixtyEight = 'sixty-eight'
    SixtyNine = 'sixty-nine'
    Seventy = 'seventy'
    SeventyOne = 'seventy-one'
    SeventyTwo = 'seventy-two'
    SeventyThree = 'seventy-three'
    SeventyFour = 'seventy-four'
    SeventyFive = 'seventy-five'
    SeventySix = 'seventy-six'
    SeventySeven = 'seventy-seven'
    SeventyEight = 'seventy-eight'
    SeventyNine = 'seventy-nine'
    Eighty = 'eighty'
    EightyOne = 'eighty-one'
    EightyTwo = 'eighty-two'
    EightyThree = 'eighty-three'
    EightyFour = 'eighty-four'
    EightyFive = 'eighty-five'
    EightySix = 'eighty-six'
    EightySeven = 'eighty-seven'
    EightyEight = 'eighty-eight'
    EightyNine = 'eighty-nine'
    Ninety = 'ninety'
    NinetyOne = 'ninety-one'
    NinetyTwo = 'ninety-two'
    NinetyThree = 'ninety-three'
    NinetyFour = 'ninety-four'
    NinetyFive = 'ninety-five'
    NinetySix = 'ninety-six'
    NinetySeven = 'ninety-seven'
    NinetyEight = 'ninety-eight'
    NinetyNine = 'ninety-nine'
    OneHundred = 'one-hundred'
    OneHundredOne = 'one-hundred-one'
    OneHundredTwo = 'one-hundred-two'
    OneHundredThree = 'one-hundred-three'


class PerRGB(Zone):
    Logo = 'logo'
    A = 'a'
    B = 'b'
    C = 'c'
    D = 'd'
    E = 'e'
    F = 'f'
    G = 'g'
    H = 'h'
    I = 'i'
    J = 'j'
    K = 'k'
    L = 'l'
    M = 'm'
    N = 'n'
    O = 'o'
    P = 'p'
    Q = 'q'
    R = 'r'
    S = 's'
    T = 't'
    U = 'u'
    V = 'v'
    W = 'w'
    X = 'x'
    Y = 'y'
    Z = 'z'
    Keyboard0 = 'keyboard-0'
    Keyboard1 = 'keyboard-1'
    Keyboard2 = 'keyboard-2'
    Keyboard3 = 'keyboard-3'
    Keyboard4 = 'keyboard-4'
    Keyboard5 = 'keyboard-5'
    Keyboard6 = 'keyboard-6'
    Keyboard7 = 'keyboard-7'
    Keyboard8 = 'keyboard-8'
    Keyboard9 = 'keyboard-9'
    Return = 'return'
    Escape = 'escape'
    Backspace = 'backspace'
    Tab = 'tab'
    SpaceBar = 'spacebar'
    Caps = 'caps'
    Dash = 'dash'
    Equal = 'equal'
    LBracket = 'l-bracket'
    RBracket = 'r-bracket'
    Backslash = 'backslash'
    Pound = 'pound'
    Semicolon = 'semicolon'
    Quote = 'quote'
    Backquote = 'backquote'
    Comma = 'comma'
    Period = 'period'
    Slash = 'slash'
    F1 = 'f1'
    F2 = 'f2'
    F3 = 'f3'
    F4 = 'f4'
    F5 = 'f5'
    F6 = 'f6'
    F7 = 'f7'
    F8 = 'f8'
    F9 = 'f9'
    F10 = 'f10'
    F11 = 'f11'
    F12 = 'f12'
    PrintScreen = 'printscreen'
    ScrollLock = 'scrolllock'
    Pause = 'pause'
    Insert = 'insert'
    Home = 'home'
    PageUp = 'pageup'
    Delete = 'delete'
    End = 'end'
    PageDown = 'pagedown'
    RightArrow = 'rightarrow'
    LeftArrow = 'leftarrow'
    DownArrow = 'downarrow'
    UpArrow = 'uparrow'
    KeypadNumLock = 'keypad-num-lock'
    KeypadDivide = 'keypad-divide'
    KeypadTimes = 'keypad-times'
    KeypadMinus = 'keypad-minus'
    KeypadPlus = 'keypad-plus'
    KeypadEnter = 'keypad-enter'
    KeypadPeriod = 'keypad-period'
    Keypad0 = 'keypad-0'
    Keypad1 = 'keypad-1'
    Keypad2 = 'keypad-2'
    Keypad3 = 'keypad-3'
    Keypad4 = 'keypad-4'
    Keypad5 = 'keypad-5'
    Keypad6 = 'keypad-6'
    Keypad7 = 'keypad-7'
    Keypad8 = 'keypad-8'
    Keypad9 = 'keypad-9'
    LCtrl = 'l-ctrl'
    LShift = 'l-shift'
    LAlt = 'l-alt'
    LWin = 'l-win'
    RCtrl = 'r-ctrl'
    RShift = 'r-shift'
    RAlt = 'r-alt'
    RWin = 'r-win'
    SsKey = 'ss-key'
    WinMenu = 'win-menu'
    M0 = 'm0'
    M1 = 'm1'
    M2 = 'm2'
    M3 = 'm3'
    M4 = 'm4'
    M5 = 'm5'
    # Group
    GroupFunctionKeys = 'function-keys'
    GroupNumberKeys = 'number-keys'
    GroupQRow = 'q-row'
    GroupARow = 'a-row'
    GroupZRow = 'z-row'
    GroupMacroKeys = 'macro-keys'
    GroupAllMacroKeys = 'all-macro-keys'
    GroupMainKeyboard = 'main-keyboard'
    GroupNavCluster = 'nav-cluster'
    GroupArrows = 'arrows'
    GroupKeypad = 'keypad'
    GroupKeypadNums = 'keypad-nums'
    GroupAll = 'all'


class Tactile(Zone):
    One = 'one'


class Screen(Zone):
    One = 'one'
    Screen128x36 = 'screened-128x36'
    Screen128x40 = 'screened-128x40'
    Screen128x48 = 'screened-128x48'
    Screen128x52 = 'screened-128x52'
